name: Flutter CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore:
      - "fastlane/**"
  push:
    branches:
      - main
    paths-ignore:
      - "fastlane/**"

jobs:
  analyze-test:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: analyze-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: build/app/outputs/flutter-apk/app-release.apk
